spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      sms:
        host: https://dfsns.market.alicloudapi.com
        path: /data/send_sms
        appcode: 7633f213692145b593baf1e68e44351d
  application:
    name: gulimall-third-party
server:
  port: 30000

